### ISSUE TITLE
nmap requires library that doesn't exist

### ISSUE THREAD

**Issue by talex5** [0install/repo.roscidus.com#126]
@bastianeicher we have this, but I don't see the target library anywhere:

```xml
security/nmap.xml:    <requires interface="http://repo.roscidus.com/lib/svn-client-1">
```

(added in 9e1fe9a92a4a87f85cd9df0513c7632b8918b93e)

**Comment by bastianeicher** [comment]
Unfortunately I don't remember why I put that dependency in. It was probably accidental, since after removing it locally both `nmap` and `ndiff` seem to work fine on my Ubuntu 18.04.

I'll create a PR that removes the dependency.

**Comment by talex5** [comment]
Thanks!
